/* Generated by mds-generator. DO NOT EDIT! */
package mds.example.model.user.sql;

import org.mybatis.dynamic.sql.SqlTable;

@xyz.codemeans.mybatis.generator.annotation.MdsGenerated
public final class GeneratedDynamicSqlSupport {


  @xyz.codemeans.mybatis.generator.annotation.MdsGenerated
  public static final class Generated extends SqlTable {

    public Generated() { super("generated"); }
  }
}