/* Generated by mds-generator. DO NOT EDIT! */package mds.example.model.user.sql;

import java.sql.JDBCType;
import org.mybatis.dynamic.sql.SqlColumn;
import org.mybatis.dynamic.sql.SqlTable;
import java.time.LocalDateTime;
import java.util.List;
import mds.example.model.user.UserGender;

/** @see mds.example.model.user.UserProfile */
@xyz.codemeans.mybatis.generator.annotation.MdsGenerated
public final class UserProfileDynamicSqlSupport {
  public static final UserProfile userProfile = new UserProfile();
  /** @see mds.example.model.user.UserProfile#id */
  public static final SqlColumn<Long> id = userProfile.id;
  /** @see mds.example.model.user.UserProfile#nickname */
  public static final SqlColumn<String> nickname = userProfile.nickname;
  /** @see mds.example.model.user.UserProfile#active */
  public static final SqlColumn<Boolean> active = userProfile.active;
  /** @see mds.example.model.user.UserProfile#createAt */
  public static final SqlColumn<LocalDateTime> createAt = userProfile.createAt;
  /** @see mds.example.model.user.UserProfile#tags */
  public static final SqlColumn<List> tags = userProfile.tags;
  /** @see mds.example.model.user.UserProfile#gender */
  public static final SqlColumn<UserGender> gender = userProfile.gender;
  /** @see mds.example.model.user.UserProfile#arr */
  public static final SqlColumn<int[]> arr = userProfile.arr;
  /** @see mds.example.model.ModelParent#updateAt */
  public static final SqlColumn<LocalDateTime> updateAt = userProfile.updateAt;

  /** @see mds.example.model.user.UserProfile */
  @xyz.codemeans.mybatis.generator.annotation.MdsGenerated
  public static final class UserProfile extends SqlTable {
    /** @see mds.example.model.user.UserProfile#id */
    public final SqlColumn<Long> id = column("id", JDBCType.BIGINT);
    /** @see mds.example.model.user.UserProfile#nickname */
    public final SqlColumn<String> nickname = column("nickname", JDBCType.VARCHAR);
    /** @see mds.example.model.user.UserProfile#active */
    public final SqlColumn<Boolean> active = column("active", JDBCType.BOOLEAN);
    /** @see mds.example.model.user.UserProfile#createAt */
    public final SqlColumn<LocalDateTime> createAt = column("create_at", JDBCType.TIMESTAMP);
    /** @see mds.example.model.user.UserProfile#tags */
    public final SqlColumn<List> tags = column("tags", JDBCType.VARCHAR);
    /** @see mds.example.model.user.UserProfile#gender */
    public final SqlColumn<UserGender> gender = column("gender", JDBCType.VARCHAR);
    /** @see mds.example.model.user.UserProfile#arr */
    public final SqlColumn<int[]> arr = column("arr", JDBCType.VARCHAR);
    /** @see mds.example.model.ModelParent#updateAt */
    public final SqlColumn<LocalDateTime> updateAt = column("update_at", JDBCType.TIMESTAMP);

    public UserProfile() { super("user_profile"); }
  }

  /** @see mds.example.model.user.UserProfile */
  @xyz.codemeans.mybatis.generator.annotation.MdsGenerated
  public interface UserProfileFields {
    /** @see mds.example.model.user.UserProfile#id */
    String id = "id";
    /** @see mds.example.model.user.UserProfile#nickname */
    String nickname = "nickname";
    /** @see mds.example.model.user.UserProfile#active */
    String active = "active";
    /** @see mds.example.model.user.UserProfile#createAt */
    String createAt = "createAt";
    /** @see mds.example.model.user.UserProfile#tags */
    String tags = "tags";
    /** @see mds.example.model.user.UserProfile#gender */
    String gender = "gender";
    /** @see mds.example.model.user.UserProfile#arr */
    String arr = "arr";
    /** @see mds.example.model.ModelParent#updateAt */
    String updateAt = "updateAt";
  }
}